### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by castamonte** [B-DNS/Firefox#3] opened 2017-09-25 15:19 UTC
when I try open site in .lib domain I get only 502 Bad Gateway
Firefox 55, Ubuntu 17.04
.bit works great

**Comment by astanze** [comment] 2017-10-12 18:51
502 is most certainly returned by the website itself. BDNS addon doesn't change page contents in any way and it cannot produce HTTP errors. If there are problems with the addon, you will see a popup notification, nothing else.

To make sure, you can use a third party proxy:

```
http://proxy.opennicproject.org/proxy.php?q=DOMAIN.BTLD
http://DOMAN.LIB.emergate.net/
```

(emergate is only for Emercoin domains)

Examples:

* http://proxy.opennicproject.org/proxy.php?q=bdns.bit
* http://bdns.lib.emergate.net/

**Comment by astanze** [comment] 2017-10-19 17:06
I'm closing this issue since the problem is likely not on BDNS' side. Please reopen it if you believe that's not the case.

**Closed as completed by astanze** 2017-10-19 17:06 UTC
